apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 200m
    defaultRequest: # this section defines default requests
      cpu: 100m
    max:
      cpu: "1"
    min:
      cpu: 50m
    type: Container
