apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    project: practice
    author: doston
  name: nginx2
  namespace: exam-doston
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
